services:
  backend-dev:
    container_name: template-backend-dev
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./apps/backend/src:/app/src
    networks:
      - template-network-dev
    command: >
      uv run uvicorn src.app:app --reload --host 0.0.0.0 --port 8000
    profiles:
      - dev

  backend:
    container_name: template-backend
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - template-network
    command: >
      uv run --locked --compile-bytecode uvicorn src.app:app --host 0.0.0.0 --port 8000
    profiles:
      - prod

  backend-test-e2e:
    container_name: template-backend-test-e2e
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    env_file: .env
    # networks:
    #   - template-network
    command: >
      uv run --group test pytest tests/e2e
    profiles:
      - test
      - test-e2e

  backend-test-unit:
    container_name: template-backend-test-unit
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    env_file: .env
    # networks:
    #   - template-network
    command: >
      uv run --group test pytest tests/unit
    profiles:
      - test
      - test-unit

  node_exporter:
    container_name: template-node-exporter
    image: quay.io/prometheus/node-exporter:v1.9.1
    volumes:
      - node-exporter-data:/host:ro,rslave
    networks:
      - template-network
    command:
      - --path.rootfs=/host
    profiles:
      - prod

  prometheus:
    container_name: template-prometheus
    image: prom/prometheus:v3.3.0
    volumes:
      - ./etc/prometheus:/etc/prometheus
    networks:
      - template-network
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    profiles:
      - prod

  alertmanager:
    container_name: template-alertmanager
    build:
      context: ./etc/alertmanager
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - template-network
    depends_on:
      prometheus:
        condition: service_started
      backend:
        condition: service_started
    profiles:
      - prod

  grafana:
    container_name: template-grafana
    image: grafana/grafana:11.6.1
    env_file: .env
    volumes:
      - grafana-data:/var/lib/grafana
      - ./etc/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./etc/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./etc/grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - template-network
    depends_on:
      prometheus:
        condition: service_started
    profiles:
      - prod

  nginx-dev:
    container_name: template-nginx-dev
    image: nginx:1.28.0
    depends_on:
      backend-dev:
        condition: service_started
    volumes:
      - ./etc/nginx/conf.d/default.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 443:443
      - 80:80
    networks:
      - template-network-dev
    profiles:
      - dev

  nginx-prod:
    container_name: template-nginx-prod
    image: nginx:1.28.0
    depends_on:
      backend:
        condition: service_started
      grafana:
        condition: service_started
    volumes:
      - ./etc/nginx/conf.d/default.prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 443:443
      - 80:80
    networks:
      - template-network
    profiles:
      - prod

volumes:
  node-exporter-data:
    name: node-exporter-data
  grafana-data:
    name: grafana-data

networks:
  template-network:
    name: template-network
    driver: bridge
  template-network-dev:
    name: template-network-dev
    driver: bridge
