FROM python:3.13-alpine

WORKDIR /app

COPY requirements/common.txt requirements/common.txt
COPY requirements/dev.txt requirements/dev.txt

RUN pip install -r requirements/dev.txt

COPY src src
COPY pyproject.toml pyproject.toml

CMD sh -c "alembic upgrade head && uvicorn src.app:app --reload --host 0.0.0.0 --port 8000"
