FROM python:3.13-alpine

WORKDIR /backend

COPY requirements/common.txt requirements/common.txt
COPY requirements/test.txt requirements/test.txt

RUN pip install -r requirements/test.txt

COPY src src
COPY tests tests
COPY pyproject.toml pyproject.toml

CMD sh -c "pytest tests/e2e"
