name: Build Backend Docker Image

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_call:

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend image
        run: docker build -t ${{ secrets.IMAGE_NAME }}-backend:${{ github.sha }} ./apps/backend

      - name: Tag backend image
        run: |
          docker tag ${{ secrets.IMAGE_NAME }}-backend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}-backend:latest
          docker tag ${{ secrets.IMAGE_NAME }}-backend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}-backend:${{ github.sha }}

      - name: Push backend image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}-backend:${{ github.sha }}
