global:
  resolve_timeout: 5m

route:
  receiver: "telegram"

receivers:
  - name: "telegram"
    telegram_configs:
      - chat_id: ${ALERTMANAGER_TELEGRAM_CHAT_ID}
        bot_token: ${ALERTMANAGER_TELEGRAM_BOT_TOKEN}
        message: |
          {{ if .CommonAnnotations.title -}}
            <b>{{ .CommonAnnotations.title | safeHtml }}</b>
          {{- end }}

          {{ if .CommonAnnotations.description -}}
            {{ .CommonAnnotations.description | safeHtml }}
          {{- end }}
