name: Build Frontend Docker Image

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      IMAGE_NAME:
        required: true

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build frontend image
        working-directory: apps/frontend
        run: |
          docker build \
            -f Dockerfile.prod \
            --build-arg API_URL=http://backend:8000/api/ \
            -t ${{ secrets.IMAGE_NAME }}-frontend:${{ github.sha }} .

      - name: Tag frontend image
        run: |
          docker tag ${{ secrets.IMAGE_NAME }}-frontend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}-frontend:latest
          docker tag ${{ secrets.IMAGE_NAME }}-frontend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}-frontend:${{ github.sha }}

      - name: Push frontend image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}-frontend:${{ github.sha }}
