name: CD Pipeline

on:
  workflow_run:
    workflows:
      - "CI Pipeline"
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    steps:
      - name: Deploy on remote server
        run: echo "Need a remote server to deploy"
#        uses: appleboy/ssh-action@v0.1.7
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          port: 22
#          script: |
#            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}-backend:latest
#            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}-frontend:latest
#            cd /root/code/${{ secrets.REPOSITORY_NAME }}
#            docker compose --profile prod up -d --build --force-recreate
