name: CI Pipeline

on:
  push: {}
  pull_request: {}

jobs:
  lint-backend:
    uses: ./github/workflows/lint-backend.yml

  lint-frontend:
    uses: ./github/workflows/lint-frontend.yml

#  unit-tests:
#    needs: [ lint-backend ]
#    uses: ./github/workflows/unit-tests.yml

#  e2e-tests:
#    needs: [ unit-tests ]
#    uses: ./github/workflows/e2e-tests.yml
#
  build-backend:
    needs: [ lint-backend ]
    uses: ./github/workflows/build-backend.yml

  build-frontend:
    needs: [ lint-frontend ]
    uses: ./github/workflows/build-frontend.yml