name: CI Pipeline

on:
  push: {}
  pull_request: {}

jobs:
  lint-backend:
    uses: ./.github/workflows/stages/backend/lint-backend.yml

  lint-frontend:
    uses: ./.github/workflows/stages/frontend/lint-frontend.yml

  unit-tests:
    needs: [ lint-backend ]
    uses: ./.github/workflows/stages/backend/unit-tests.yml

#  e2e-tests:
#    needs: [ unit-tests ]
#    uses: ./.github/workflows/stages/backend/e2e-tests.yml
#
#  build-backend:
#    needs: [ e2e-tests ]
#    uses: ./.github/workflows/stages/backend/build-backend.yml

  build-frontend:
    needs: [ lint-frontend ]
    uses: ./.github/workflows/stages/frontend/build-frontend.yml