name: CI Pipeline

on:
  push: {}
  pull_request: {}

jobs:
  lint-backend:
    uses: ./lint-backend.yml

  lint-frontend:
    uses: ./lint-frontend.yml

  unit-tests:
    needs: [ lint-backend ]
    uses: ./unit-tests.yml

#  e2e-tests:
#    needs: [ unit-tests ]
#    uses: ./e2e-tests.yml
#
#  build-backend:
#    needs: [ e2e-tests ]
#    uses: ./build-backend.yml

  build-frontend:
    needs: [ lint-frontend ]
    uses: ./build-frontend.yml