name: CI Pipeline

on:
  push: {}
  pull_request: {}

jobs:
  lint-backend:
    uses: .github/workflows/lint-backend.yml@v1

  lint-frontend:
    uses: .github/workflows/lint-frontend.yml@v1

#  unit-tests:
#    needs: [ lint-backend ]
#    uses: .github/workflows/unit-tests.yml@v1

#  e2e-tests:
#    needs: [ unit-tests ]
#    uses: .github/workflows/e2e-tests.yml@v1
#
  build-backend:
    needs: [ lint-backend ]
    uses: .github/workflows/build-backend.yml@v1

  build-frontend:
    needs: [ lint-frontend ]
    uses: .github/workflows/build-frontend.yml@v1